file(WRITE "${OUT}" "#pragma once\nnamespace ct { namespace assets {\n")
foreach(f IN LISTS FILES)
  get_filename_component(_name "${f}" NAME_WE)
  get_filename_component(_ext "${f}" EXT)
  file(READ "${f}" _content)
  if(_ext STREQUAL ".css")
    set(_var "css_${_name}")
  else()
    set(_var "js_${_name}")
  endif()
  file(APPEND "${OUT}" "static const char ${_var}[] = R\"CTASSET(${_content})CTASSET\";\n")
endforeach()
file(APPEND "${OUT}" "}}\n")
